### ISSUE TITLE
Properly credit icon source

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-email-workitem-action#3]
According to my information, the icon used is from _fontawesome_. 
As per https://fontawesome.com/license/free, we have to properly credit them if we use an icon in our project. Read [here](https://wiki.creativecommons.org/wiki/best_practices_for_attribution) on how to properly credit _CC BY_ licensed artifacts. 

Suggestions: Credit _fontawesome_ in the _LICENSING_ section of the _README_.

**Comment by MartinBenninger** [comment]
I added the attribution at the suggested location in the readme.
